### PR TITLE
fix: share modal item width

### LINKED ISSUE #717: [UI] `ShareModal` looks teribble on mobile devices
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

before1

Those items, lenster, reddit, twitter, linkedin more specifically, are in bad shape on some mobile devices with small screen.

### Expected Behavior

after1

shape of these items keep identicial on the small screen, and x-axis is scrollable.

### Steps To Reproduce

_No response_

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome, Safari

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chawyehsu**
## Description

Closes #717

- [x] I read the [contributing docs](CONTRIBUTING.md) (if this is your first contribution)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Minor changes in old functionality

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by sasicodes** [comment]
@chawyehsu can you share the issue this PR is fixing 🙇🏻 ?

**Comment by chawyehsu** [comment]
@sasicodes thanks for reviewing, see #717 for the issue.

**Comment by sasicodes** [comment]
> @sasicodes thanks for reviewing, see #717 for the issue.

got it, what happen when we try `flex-none`?

**Comment by chawyehsu** [comment]
> got it, what happens when we try flex-none?

Sorry I don't get it. where do you want to put `flex-none`? the parent `div`? If so, I don't think it helps in terms of the issue.

**Comment by sasicodes** [comment]
> > got it, what happens when we try flex-none?
> 
> Sorry I don't get it. where do you want to put `flex-none`? the parent `div`? If so, I don't think it helps in terms of the issue.

I mean if we try flex-none instead of max-w-none, does it work?

**Comment by chawyehsu** [comment]
> I mean if we try flex-none instead of max-w-none, does it work?

nah, it doesn't help.

image

**Review by sasicodes — APPROVED** [review]

**Comment by sasicodes** [comment]
thanks for the PR @chawyehsu 💯

**Pull request merged**
