### PR TITLE
chore: added button role to divs with click handlers

### LINKED ISSUE #371: (JS-0765) Prefer that non-interactive, visible elements (such as <div>) that have click handlers use the role attribute
## Description
Static HTML elements do not have semantic meaning. This is clear in the case of `&lt;div&gt;` and `&lt;span&gt;`. It is less so clear in the case of elements that _seem_ semantic, but that do not have a semantic mapping in the accessibility layer. For example `&lt;a&gt;`, `&lt;big&gt;`, `&lt;blockquote&gt;`, `&lt;footer&gt;`, `&lt;picture&gt;`, …

## Occurrences
There are 13 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0765/occurrences/](https://deepsource.io/gh/lenstube-xyz/lenstube/issue/JS-0765/occurrences/)

### PR DESCRIPTION
**Pull request by zt4ff**
## Description

Closes #371

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by sasicodes** [comment]
@zt4ff  can you delete the yarn.lock changes?

**Comment by zt4ff** [comment]
@sasicodes 
I think you removed the yarn.lock changes from this file changed in this PR
I can't find it here: https://github.com/lenstube-xyz/lenstube/pull/397/files

**Review by sasicodes — APPROVED** [review]

**Comment by sasicodes** [comment]
LGTM

**Comment by sasicodes** [comment]
@zt4ff please collect you gitpoap

**Comment by zt4ff** [comment]
> @zt4ff please collect you gitpoap

Thanks. I already collected it.

**Pull request merged**
